### ISSUE TITLE
메인 페이지 로고 추가

### ISSUE THREAD

**Issue by happy-nut** [happy-nut/happy-nut.github.io#5]

**Comment by poqw** [comment]
반응형 대응도 하자.

일정 너비 이하에선 오른편에 햄버그 메뉴 등장하도록 하면 될 듯 

로고는 스크린 줄든 / 페이지를 이동하든 항상 그 자리에 있게?

헤더 포지션을 fixed로 할지는 고민이긴 한데.. fixed로 해놨다가 이상해 질것 같으면 바꾸자.
